/**
 * v3.9c-tactical P4 — per-product OG image URL registry.
 *
 * Every product's OG image is imported from app/assets/og/<slug>.png.
 * Vite bundles the PNG and resolves the import to a CDN URL with a
 * content hash (Oxygen-served, identical pattern to the v3.9 product
 * covers). The hash is computed at build time, so the URLs can't be
 * hardcoded — callers read them through getOgImageUrl(slug).
 *
 * The PNGs themselves are generated by scripts/generate-og-images.mjs
 * (npm run generate-og). Run that script whenever a cover changes or
 * a new product is added, then commit the regenerated PNGs.
 */

import {SITE_URL} from '~/components/promptos/JsonLd';

// v3.9a covers
import marketerOg from '~/assets/og/marketer.png';
import personalBrandOg from '~/assets/og/personal-brand.png';
import everythingOg from '~/assets/og/everything.png';

// v3.9b packs
import writerOg from '~/assets/og/writer.png';
import developerOg from '~/assets/og/developer.png';
import solopreneurOg from '~/assets/og/solopreneur.png';
import contentCreatorOg from '~/assets/og/content-creator.png';
import aiPowerUserOg from '~/assets/og/ai-power-user.png';
import productivityOg from '~/assets/og/productivity.png';

// v3.9b playbooks
import aiAutomationAgencyOg from '~/assets/og/ai-automation-agency.png';
import aiAgentBuilderOg from '~/assets/og/ai-agent-builder.png';
import webDesignAgencyOg from '~/assets/og/web-design-agency.png';
import digitalProductsOg from '~/assets/og/digital-products.png';
import newsletterBusinessOg from '~/assets/og/newsletter-business.png';
import facelessContentOg from '~/assets/og/faceless-content.png';
import saasSideProjectOg from '~/assets/og/saas-side-project.png';
import coachingConsultingOg from '~/assets/og/coaching-consulting.png';

// v3.9b Authority + bundles
import contentEngineOg from '~/assets/og/content-engine.png';
import highTicketFinderOg from '~/assets/og/high-ticket-finder.png';
import packsBundleOg from '~/assets/og/packs.png';
import authorityBundleOg from '~/assets/og/authority.png';
import guidesBundleOg from '~/assets/og/guides.png';

const OG_MAP: Record<string, string> = {
  marketer: marketerOg,
  'personal-brand': personalBrandOg,
  everything: everythingOg,
  writer: writerOg,
  developer: developerOg,
  solopreneur: solopreneurOg,
  'content-creator': contentCreatorOg,
  'ai-power-user': aiPowerUserOg,
  productivity: productivityOg,
  'ai-automation-agency': aiAutomationAgencyOg,
  'ai-agent-builder': aiAgentBuilderOg,
  'web-design-agency': webDesignAgencyOg,
  'digital-products': digitalProductsOg,
  'newsletter-business': newsletterBusinessOg,
  'faceless-content': facelessContentOg,
  'saas-side-project': saasSideProjectOg,
  'coaching-consulting': coachingConsultingOg,
  'content-engine': contentEngineOg,
  'high-ticket-finder': highTicketFinderOg,
  packs: packsBundleOg,
  authority: authorityBundleOg,
  guides: guidesBundleOg,
};

/**
 * Returns the absolute (CDN-resolved) URL for a product's OG image.
 * Falls back to the existing /og-default.png if the slug is unknown.
 * Returns undefined when running on a stripped build that doesn't
 * include the OG bundle (defensive — should never happen on prod).
 */
export function getOgImageUrl(slug: string): string | undefined {
  const local = OG_MAP[slug];
  if (!local) return undefined;
  // Vite import is already an absolute (CDN-hashed) URL at build
  // time. For meta + JSON-LD we want a fully-qualified URL — local
  // is `/oxygen-v2/.../assets/<slug>-<hash>.png` so we prepend the
  // site origin only if it's not already absolute.
  if (/^https?:\/\//i.test(local)) return local;
  return `${SITE_URL}${local}`;
}

/** True when an OG image is registered for this slug. */
export function hasOgImage(slug: string): boolean {
  return slug in OG_MAP;
}
